% /////// translate_data ///////
% Enables you to move the data line on a plot generated by
% fv_calibrate_points.m in either the x,y or both directions. If the plot
% has not been created by fv_calibrate_points.m then the timeseries which
% you wish to fiddle with must have the 'Tag' property set to 'data'. You can do
% this by clicking on the line before typing set(gco,'Tag','data')
% Once translate_data has been called the select icon must be unselected before you can translate the lines
%
% inputs
%   f = handle to figure generated by fv_calibrate_points
%   trans = in which direction to enable translating. 'x','y','xy'
%
% Jesper Nielsen, March 2014

function translate_data(f,trans)

% check
switch get(f,'Type')
    case 'figure'
    otherwise
        display('first input must be a handle to a figure object')
        return
end

% handle to data timeseries
h = findobj(f,'Tag','data');
nh = length(h);

% use the wonder function translate_graphics
% -- loop through objects
for aa = 1:nh
    ax = ancestor(h(aa),'axes');
    hgt = hgtransform('parent',ax,'HittestArea','off','hittest','off');
    hgg = hggroup('parent',hgt,'hittest','on','buttondownfcn',{@translate_graphics,trans});
    set(h(aa),'parent',hgg,'hittest','off')
end


