% FVRES_CURTAIN     TUFLOW-FV curtain results object
%
%   resObj = fvres_curtain(resfil,geofil,pline) creates a curtain results object.
%   resfil is the cell-centre netcdf results file generated by TUFLOW-FV,
%   geofil is the netcdf geometry file created
%   by TUFLOW-FV & pline is a set of points which define the curtain.
%
%   resObj = fvres_curtain(resfil,geofil,pline,'PropertyName',PropertyValue,...) creates
%   a curtain results object defined by the specified property name / property value
%   pairs. Default values are assigned to all unspecified properties.
%
%   Execute get(resObj), to see a list of the resObj's properties and
%   their current values.
%
%   Execute set(resObj,'PropertyName',PropertyValue) to change a
%   property of an existing resObj.
%
%
%   /-/-/-/-/-/-/-/-/ EXAMPLES /-/-/-/-/-/-/-/-/
%
%   (1): Create a resObj containing salinity and temperature results for a curtain defined by 2 points
%   resObj = fvres_curtain('mymodel.nc','mymodel_geo.nc',[p1_x p1_y; p2_x p2_y],'variables',{'SAL';'TEMP'})
%
%   (2): Change the location of the curtain from which the results are extracted
%   set(resObj,'Pline',[p3_x p3_y; p4_x p4_y])
%
%
%   /-/-/-/-/-/-/-/-/ PROPERTIES /-/-/-/-/-/-/-/-/
%
%   Type           ==> fvres_curtain
%
%   Resfil         ==> TUFLOW-FV cell-centre netcdf results file
%
%   Geofil         ==> TUFLOW-FV netcdf geometry file
%
%   Pline          ==> A set of points which define the curtainObj 
%
%   Chainage       {false} | true ==> provide the cellface intersections for plotting against chainage using fvg_curtain
%
%   TimeVector     ==> vector of output times within Resfil
%
%   TimeCurrent    ==> output time corresponding to results in resObj
%
%   TimeStep       ==> integer timestep corresponding to results in resObj
%
%   Variables      ==> variable to extract along Pline
% 
%   ResultsCurtain ==> structure containing results extracted along Pline
%
%
%
% See also FVRES_SHEET
%
% http://tuflow.com/fvforum/index.php?/forum/16-matlab/
% http://fvwiki.tuflow.com/index.php?title=MATLAB_TUTORIAL
%
% Jesper Nielsen, Copyright (C) BMTWBM 2014

classdef (CaseInsensitiveProperties = true) fvres_curtain < fvres
    properties (Constant)
        Type = 'fvres_curtain'
    end
    properties
        Pline
        Chainage
        ResultsCurtain = struct();
    end
    properties (Dependent = true)
    end
    properties (Hidden = true)
        faces
        vertices
    end
    methods
        % // constructor method //
        function obj = fvres_curtain(resfil,geofil,pline,varargin)
            % Pre-initialization — Compute arguments for superclass constructor
            
            % Object initialization — Call superclass constructor
            obj@fvres(resfil);
            
            % Post initialization — Perform any operations related to the subclass, including referencing and assigning to the object, call class methods, passing the object to functions, and so on
            obj.Geofil = geofil;
            obj.Pline = pline; % fire the callback

            % -- optional inputs
            noi = length(varargin);
            if mod(noi,2) ~= 0
                error('expecting optional inputs as property / value pairs')
            end
            for aa = 1:2:noi
                set(obj,varargin{aa},varargin{aa+1});
            end
        end
        % // set methods //
        function set.Pline(obj,val)
            obj.Pline = val;
            obj.WORK.refresh = true;
            workhorse(obj);
        end
        function set.Chainage(obj,val)
            obj.Chainage = val;
            obj.WORK.refresh = true;
            workhorse(obj);
        end
        % // get methods //
        % // retrieve and process results //
        function workhorse(obj)
            obj = fv_get_curtain2(obj);
            obj.notify('update_patches')
        end
    end
end
% // sub functions //

